[project]
name = "dicomsorter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydicom>=3.0.1",
]

[project.scripts]
ds = "dicomsorter.app:main"

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.tagerts.wheel]
packages = ['src/dicomsorter']
